name: CI

on: push

jobs:
  build:
    name: 🏗️ Gradle build
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v4
      - name: 🧰 Install JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: gradle
      - name: 🧰 Install Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '6.5'
      - name: 🏗️ Build with Gradle
        run: ./gradlew build
  test:
    needs: build
    name: ✅ Gradle test
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v4
      - name: 🧰 Install JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: gradle
      - name: 🧰 Install Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '6.5'
      - name: ✅ Test with Gradle
        run: ./gradlew test
